{% set name = "specreduce" %}
{% set version = "1.7.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/specreduce-{{ version }}.tar.gz
  sha256: d347f9bb1d5ef98f3a25c265d7e74af94021f30bc0d388a18fc5bc15fbe5005d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python  {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - astropy-base
    - matplotlib-base >=3.10
    - scipy
    - specutils >=1.9.1
    - gwcs

test:
  imports:
    - specreduce
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/astropy/specreduce
  summary: Astropy coordinated package for Spectroscopic Reductions
  license: BSD-3-Clause
  license_file: licenses/LICENSE.rst

extra:
  recipe-maintainers:
    - hpparvi
    - mwcraig
