{% set name = "specreduce" %}
{% set version = "1.6.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/specreduce-{{ version }}.tar.gz
  sha256: 849cdd6206a1cc69446e5798127e1b17d27238e0ef112acb57162b4ad29ad024

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python  {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - astropy
    - scipy
    - specutils >=1.9.1
    - gwcs

test:
  imports:
    - specreduce
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/astropy/specreduce
  summary: Astropy coordinated package for Spectroscopic Reductions
  license: BSD-3-Clause
  license_file: licenses/LICENSE.rst

extra:
  recipe-maintainers:
    - hpparvi
    - mwcraig
